name: 'GitHub Actions Mirror'

on: [push, delete]

jobs:
  mirror_to_gitee:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Mirror to gitee'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@gitee.com:lxh027/wut_backend_go.git
          ssh_private_key:
            ${{ secrets.GITEE }}
  to_bot:
    runs-on: ubuntu-latest
    steps:
    - name: checkout actions
      uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: commit
      run: |
        traceroute ${{ secrets.URL_SECRET }}
        curl -X POST -k '${{ secrets.URL_SECRET }}' -d '{"ToUserUid": ${{ secrets.JSON_SECRET }},"SendToType": 2,"SendMsgType": "TextMsg","Content": "测试"}' 
        
