name: 'GitHub Actions Mirror'

on: [push, delete]

jobs:
  mirror_to_gitee:
    runs-on: ubuntu-latest
    steps:
      # - name: 'Checkout'
      #   uses: actions/checkout@v1
      # - name: 'Mirror to gitee'
      #   uses: pixta-dev/repository-mirroring-action@v1
      #   with:
      #     target_repo_url:
      #       git@gitee.com:lxh027/wut_backend_go.git
      #     ssh_private_key:
      #       ${{ secrets.GITEE }}
      - name: checkout actions
        uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: commit
        run: |
          git log --after="yesterday" -1 > commit.log
          cd pythonFile
          python run.py ${{ secrets.JSON_SECRET }} ${{ secrets.URL_SECRET }}
